name: waste_tracker
description: "A new Flutter project for waste tracking."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  cupertino_icons: ^1.0.8
  flutter_geofence: ^0.4.4
  geofencing_api: ^2.0.0
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
